### ISSUE TITLE
please tell how do i host it i really need this autocatcher 

### ISSUE THREAD

**Issue by SoulHunter287** [Yashar-Nishaburi/POKE-BOT#1]
please tell how to host it

**Comment by Yashar-Nishaburi** [comment]
You can simply run it with the default Python IDLE. The ReadMe explains what info you need to enter into the code in order to run it. I've also included instructions inside the code itself to hopefully make navigating it easier.  
If you want to run the catcher and the spammer at the same time, you need to open two IDLEs at through terminal. There are multiple stack overflow threads covering how to do that! 
Sorry for the extremely late response, Hope this was helpful!
